HOST_ADDRESS = "127.0.0.1"
HOST_PORT = 4589

ENABLE_DEBUG = False

USER_LIST_FILE_PATH = "/etc/passwd"
GROUP_LIST_FILE_PATH = "/etc/groups"

USER_NAME_KEY = "name"
USER_ID_KEY = "uid"
PRIMARY_GROUP_ID_KEY = "gid"
COMMENT_KEY = "comment"
HOME_PATH_KEY = "home"
SHELL_PATH_KEY = "shell"
USER_KEYS = [USER_NAME_KEY, "", USER_ID_KEY, PRIMARY_GROUP_ID_KEY, COMMENT_KEY, HOME_PATH_KEY, SHELL_PATH_KEY]

GROUP_NAME_KEY = "name"
GROUP_ID_KEY = "gid"
GROUP_LIST_KEY = "members"
GROUP_KEYS = [GROUP_NAME_KEY, "", GROUP_ID_KEY, GROUP_LIST_KEY]  # members split by ,

MESSAGE_KEY = "message"
STATUS_KEY = "status"
